apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-11-15T23:28:32Z"
  generation: 1
  labels:
    app: angular-app
  name: angular-app
  namespace: project
  resourceVersion: "263663"
  uid: 4134e382-cc8f-4a3e-9e9d-e3df4ebe292d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: angular-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: angular-app
    spec:
      containers:
      - image: malikdevops/angular-project:latest
        imagePullPolicy: Always
        name: angular-project
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-15T23:28:56Z"
    lastUpdateTime: "2023-11-15T23:28:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-15T23:28:32Z"
    lastUpdateTime: "2023-11-15T23:28:56Z"
    message: ReplicaSet "angular-app-67fc84db58" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
